### ISSUE TITLE
How to create key.json file for service accounts?

### ISSUE THREAD

**Issue by mrPsycho** [yandex-cloud/terraform-provider-yandex#303]
Hello, 

to make it possible resync images, i'm trying to do that:
```
resource "yandex_iam_service_account" "sa-docker" {
  name        = "sa-docker"
  description = "service account to manage docker containers"
  folder_id   = yandex_resourcemanager_folder.default.id
}

resource "yandex_iam_service_account_key" "sa-docker-key" {
  service_account_id = yandex_iam_service_account.sa-docker.id
  description        = "key for service account"
  key_algorithm      = "RSA_4096"
}

data "template_file" "some" {
  template = file("files/some.cloud.config")
  vars = {
    key_id                   = yandex_iam_service_account_key.sa-docker-key.id
    service_account_id       = yandex_iam_service_account.sa-docker.id
    created_at               = yandex_iam_service_account_key.sa-docker-key.created_at
    key_algorithm            = yandex_iam_service_account_key.sa-docker-key.key_algorithm
    public_key               = yandex_iam_service_account_key.sa-docker-key.public_key
    private_key              = yandex_iam_service_account_key.sa-docker-key.private_key
  }
```

template looks like this:
```
write_files:
  - owner: root:root
    path: /root/.ya.json
    content: '{"id": "${key_id}","service_account_id": "${service_account_id}", "created_at": "${created_at}", "key_algorithm": "${key_algorithm}", "public_key": "${public_key}", "private_key": "${private_key}"}'
```

and file /root/.ya.json looks correct, jq parse it without any issues. 
but `cat /root/.ya.json | docker login --username json_key --password-stdin cr.yandex`
throw that: 
```
Error response from daemon: Get "https://cr.yandex/v2/": unauthorized: Password is invalid - must be JSON key. Read more: https://cloud.yandex.ru/docs/container-registry/operations/authentication#sa-json ; requestId = c4369c25-2c56-4a6d-a50e-7fa301d9f147
```

why? if this is a correct json?

and why i think that this is bug in terraform provider:
* "created_at" has shorter value, that it is seen in json file, which is being retrieved from web ui.
* "public_key" and "private_key" have spaces instead of `\n`, like it is in json from ui.
